### ISSUE TITLE
Set up auto-publishing webhook so changes to lp:usn.ubuntu.com go live immediately

### ISSUE THREAD

**Issue by nottrobin** [canonical/usn.ubuntu.com#10]
... And work with the Security team to ensure they can push releases live automatically.

**Comment by WillMoggridge** [comment]
Webhook set up here:
https://code.launchpad.net/~canonical-webmonkeys/usn.ubuntu.com/+git/usn.ubuntu.com-1/+webhooks

It can't talk to Jenkins, so an RT has been created:
https://portal.admin.canonical.com/107626
