### ISSUE TITLE
Show more latest items on homepage

### ISSUE THREAD

**Issue by WillMoggridge** [canonical/usn.ubuntu.com#16]
We currently show 8 of the latest items on the homepage.

Consider increasing this, and/or adding a link at the bottom to view more.

**Comment by tyhicks** [comment]
Increasing the number would be nice but I think a link at the bottom to view more is essential.

**Comment by WillMoggridge** [comment]
Merge proposal to add pagination (with 10 items in a page):
https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/337941

**Comment by nottrobin** [comment]
Merged
