### ISSUE TITLE
Months page limiting each month to 8 items

### ISSUE THREAD

**Issue by WillMoggridge** [canonical/usn.ubuntu.com#19]
The `/months` page shows all months with 8 items per section. This could be misleading, we should show all items (which sounds like it brings up page length issues) or try to create a page per month and link to them.

I believe I remember this page was a bit more complicated than others to create. If this is not so trivial, is this page required for release or could we work on it after the initial release?

**Comment by nottrobin** [comment]
Merge proposal ready: https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/338500

**Comment by nottrobin** [comment]
Approved and merged
