### ISSUE TITLE
Links to source packages are broken

### ISSUE THREAD

**Issue by WillMoggridge** [canonical/usn.ubuntu.com#21]
There are links in some notices that link to Launchpad source packages but result in a 404.

This happens on the currently live site as well as this new site. Investigate what is causing these broken URLs.

## Examples
https://usn.ubuntu.com/3311-2 contains a link to `3.2.3-2ubuntu2.1` which returns a 404.
https://lists.ubuntu.com/archives/ubuntu-security-announce/2017-April/thread.html contains a list to more examples.

**Comment by stevebeattie** [comment]
https://usn.ubuntu.com/usn/usn-3311-2/ is an update for Ubuntu 12.04 ESM which is extended support bits for the end-of-life Ubuntu 12.04 LTS. Build/package records for the ESM release are unfortunately not public.

**Comment by tyhicks** [comment]
Fixed:

https://git.launchpad.net/usn.ubuntu.com/commit/?id=5405c28c63180d7e5818a8ad8df60c9346a1a328

(I can't close this bug myself)
