### ISSUE TITLE
Incorrect formatting for dates

### ISSUE THREAD

**Issue by tyhicks** [canonical/usn.ubuntu.com#25]
On the landing page, the individual USN pages, and possibly other pages, the date is formatted incorrectly:

`8nd February 2018`

It should be:

`8th February, 2018`

The two issues are:

1. "8nd" instead of "8th"
1. Missing comma after the month

**Comment by WillMoggridge** [comment]
I think the preferred option for this would be to bring it to match the date format we use across our sites.

In our other sites (such as https://www.ubuntu.com/) we follow a guideline to list dates as:
`13 February 2018` / `DD Month YYYY`

**Comment by tyhicks** [comment]
@WillMoggridge that should be fine.

**Comment by WillMoggridge** [comment]
OK, brilliant. I made a merge proposal.

https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/337730

**Comment by nottrobin** [comment]
Approved and merged.
