### ISSUE TITLE
Existing, long form USN links are broken

### ISSUE THREAD

**Issue by tyhicks** [canonical/usn.ubuntu.com#26]
The following link is the style that we're using for the current website:

https://usn.ubuntu.com/usn/usn-3311-1

It doesn't get rewritten correctly with the new website and results in a 404.

**Comment by nottrobin** [comment]
Yep we just need a redirect in [the nginx file](https://git.launchpad.net/usn.ubuntu.com/tree/nginx.conf) to catch `/usn/usn-{number}` -> `/{number}'.

**Comment by WillMoggridge** [comment]
Merge proposal:
https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/337585
