### ISSUE TITLE
USN database is not served

### ISSUE THREAD

**Issue by tyhicks** [canonical/usn.ubuntu.com#27]
The existing USN website acts as the source for the USN database. I'm not sure of all the files that it serves up but here's some examples:

https://usn.ubuntu.com/usn-db/database-all.pickle.bz2
https://usn.ubuntu.com/usn-db/database-all.pickle.bz2.sha256
https://usn.ubuntu.com/usn-db/database.pickle.bz2
https://usn.ubuntu.com/usn-db/database.pickle.bz2.sha256

There are downstream consumers of these USN databases that will be broken if the new site doesn't serve up these files.

**Comment by setharnold** [comment]
I believe (hope) landscape switched to consuming json files; we have documented the URLs:

https://usn.ubuntu.com/usn-db/database.json.bz2
https://usn.ubuntu.com/usn-db/database.json.bz2.sha256
https://usn.ubuntu.com/usn-db/database-all.json.bz2
https://usn.ubuntu.com/usn-db/database-all.json.bz2.sha256

At least they are documented here: https://blueprints.launchpad.net/ubuntu/+spec/security-p-usn-database-format

Thanks

**Comment by nottrobin** [comment]
I think the best approach here is to leave the old service running and point a new domain at it (like legacy.usn.ubuntu.com or something). Then when the new application goes live at usn.ubuntu.com it can redirect those URLs to legacy.usn.ubuntu.com

I assume landscape will successfully follow 301 and 302 redirects?

So we just need to make sure we compile a full list of the URLs we need to redirect them over with redirect in [the nginx config](https://git.launchpad.net/usn.ubuntu.com/tree/nginx.conf). Might be best just to forward any `/usn-db/*` URLs to this legacy service.

**Comment by jdstrand** [comment]
IMO, I wouldn't consider the json export 'legacy'. The json and old pickle files are for machine-parseable input, the markdown is for humans. These are what landscape uses and they aren't going to start parsing markdown files. IMO landscape (and other consumers) should retrieve the machine-parseable from somewhere official.

UPDATE: landscape may still be grabbing the pickle files so I've updated the above accordingly.
UPDATE 2: the official place needs to be delivered via https

**Comment by nottrobin** [comment]
@jdstrand I'm not trying to say the json export is legacy, I'm trying to say the system which currently serves it will by that time be legacy for all purposes (e.g. the website) apart from a couple. And that hopefully before too long we'll replace the parts where it's still needed, e.g. the hosted json or pickle databases, with new solutions and properly retire the old system.

But if the "legacy" name isn't appropriate, I'm happy to name it anything else. api.usn.ubuntu.com? (may be misleading, it's pretty limited for an "API"). data.usn.ubuntu.com? Any other suggestions?

**Comment by tyhicks** [comment]
@nottrobin we cannot replace the systems which consume the json/pickle files by having them consume markdown. They're applications, such as Landscape and external Ubuntu CVE tracking tools, so having them parse markdown to extract data about which packages versions correspond to which CVEs is not appropriate.

**Comment by tyhicks** [comment]
@nottrobin could the deployment scripts fetch fresh copies of these databases from people.canonical.com/~ubuntu-security? Our current USN publication process copies the databases from people.c.c to the USN website so that would be similar in nature.

Storing them in the usn.ubuntu.com git tree is not ideal because the files are large, change for every USN publication, and would really bloat the size of the git tree.

**Comment by nottrobin** [comment]
@tyhicks Interesting, I thought you mentioned at one point that you would prefer that Landscape was pulling in the Markdown files in the long run, presumably because it would give you some more flexibility over how the content was formatted or something? Anyway that's neither here nor there at this point.

How big are these files? If we were to store the data in the repository in a plaintext format like JSON, then yes the repository would be large, but Git would be able to store each update simply as a diff, and assuming all relevant systems already have a clone of the repository, the amount of data that was passed around would be minimal. And Kubernetes would gzip the response anyway, so it shouldn't matter that the JSON isn't in bzip format at the source.

But yes we can have it pull in the databases at build time very easily, which may be simpler.

A potential issue with that is that it will bloat the size of the Docker image that we push to Kubernetes, which may slow down deployments. If the files are a few hundred megabytes or more, it would probably be better to host those files somewhere else that is optimised for hosting large files.

**Comment by tyhicks** [comment]
@nottrobin Hmm, I've never had any motivations to change how Landscape was displaying the content. What I remember saying is that the USN pickle/json formats are locked in because we have downstream consumers, such as Landscape, that depend on the existing format. Having the USN website consume the markdown files that are generated from the USN pickle file allows us to do transformations so that we can improve the web and email representations of a USN without breaking the downstream consumers of the databases.

Here are the file sizes:

```
$ du -ch database*
135M	database-all.json
20M	database-all.json.bz2
4.0K	database-all.json.bz2.sha256
4.0K	database-all.json.sha256
131M	database-all.pickle
23M	database-all.pickle.bz2
4.0K	database-all.pickle.bz2.sha256
4.0K	database-all.pickle.sha256
91M	database.json
13M	database.json.bz2
4.0K	database.json.bz2.sha256
4.0K	database.json.sha256
88M	database.pickle
15M	database.pickle.bz2
4.0K	database.pickle.bz2.sha256
4.0K	database.pickle.sha256
512M	total
```

So, actually not as large as what I'd thought. However, the pickle files are required so we can't take advantage of git's efficiencies around plaintext formats like JSON.

They can all be retrieved by appending the filename to https://people.canonical.com/~ubuntu-security/usn/

**Comment by nottrobin** [comment]
They're still big enough that I think it would be best to host them elsewhere. I prefer this more SOA approach anyway, since the website is clearly solving a different problem to the databases - it would be nice to keep the website more focused on its own MO.

Which is why for now I think the best thing is to leave the old application up *somewhere* and use that for hosting those files. Then down the line we can explore where would be a better place to host those files so we can retire the old app.

**Comment by nottrobin** [comment]
@tyhicks unless you're happy to simply redirect `https://usn.ubuntu.com/usn-db/database-all.pickle.bz2` to `https://people.canonical.com/` `~ubuntu-security/usn/database-all.pickle.bz2`

**Comment by tyhicks** [comment]
@nottrobin after speaking with some other folks, I'm hearing that people.c.c can't handle the load of hosting the USN database. The database was moved from people.c.c to the USN website in the past for that specific reason.

So, we're down to two options:

1. The usn.ubuntu.com deployment script fetches the USN database files from people.c.c as part of the docker image setup.
1. The existing USN website is re-purposed to only serve up the USN database files and the new website will simply redirect to it.

I greatly prefer option 1 because I think option 2 will result in the old service staying around for a very long time. Implementing a better way to serve up this information is a nice idea but the downstream consumers of the database will be very slow to migrate and we'll be stuck maintaining the old site.

**Comment by nottrobin** [comment]
Okay I'm more than happy to do option 2 of writing the DB-fetching stuff into the build process.

But option 1 would be quicker, and it is possible to do this without it tying our hands in the future. Let's say we setup:

https://usn.ubuntu.com/usn-db/database-all.pickle.bz2 -> 302 temporary redirect -> https://data.usn.ubuntu.com/usn-db/database-all.pickle.bz2

Firstly, as this would only be a 302, that instructs all clients to keep checking back at the original URL, https://usn.ubuntu.com/usn-db/database-all.pickle.bz2, to get this database. This leaves us free to either point it somewhere else in the future, or host it directly at that location, as we choose.

Secondly, whenever we do want to retire the old system, we can simply point data.usn.ubuntu.com at the new app, alongside usn.ubuntu.com. This would mean anyone who was erroneously checking https://data.usn.ubuntu.com/usn-db/database-all.pickle.bz2 would get the same response as if they had visited https://usn.ubuntu.com/usn-db/database-all.pickle.bz2.

This way we don't have to do the work of updating the build step, and the release process wouldn't be slowed down at all.

**Comment by tyhicks** [comment]
@nottrobin I think you got option 1 and option 2 backwards in the first two sentences but the rest of the comment makes it clear what you're talking about.

I'm alright with option 2 but I'd request that all of the USN pages be removed from the old site (data.usn.ubuntu.com) so that they don't get indexed and/or confuse users. Also, keep in mind that it means that two servers (sumac and papeda) will need to be maintained for quite a while. I don't know what Ubuntu release they're currently running. I don't expect us to be able to retire those systems for years.

Finally, I'll note that option 1's additional deployment time of fetching to USN database files from people.c.c isn't really an issue because if we go with option 2, we still have to spend just as much time to upload the USN database files from people.c.c to sumac and pepeda each time we publish a new USN.

The decision is ultimately up to you since the web team actually maintains this infrastructure. Thanks for talking through the options with us.

**Comment by nottrobin** [comment]
Yep I got them backwards, sorry about that.

Okay I given your point about having to upload the files anyway, and the need to not serve old files at the other URL. I think you're right, option 1 (hope I got that right this time) is probably best. Let's do that.

I've filed #29 instead, as this ticket is probably a bit long and confusing. So I'll close this now.
