### ISSUE TITLE
Deployments: Retry pushing the docker image 5 times

### ISSUE THREAD

**Issue by nottrobin** [canonical/usn.ubuntu.com#28]
The release process relies on pushing an image to our docker registry, which times out from time to time.

To make this more resilient we should update the deployment job to try pushing up to 5 times on failures ([Try the command multiple times in Bash](https://serverfault.com/a/521889)).

**Comment by nottrobin** [comment]
It might be a good idea to retry building the docker image a couple of times if it fails as well, as I suppose e.g. the `apt update` command might have a temporary timeout.

**Comment by WillMoggridge** [comment]
I have updated the configuration with retries:

https://jenkins.canonical.com/webteam/job/deploy-to-usn.ubuntu.com
