### ISSUE TITLE
Update the Dockerfile to pull in database files at build time, to be served by the live site

### ISSUE THREAD

**Issue by nottrobin** [canonical/usn.ubuntu.com#29]
We need [the database files](https://github.com/canonical-websites/usn.ubuntu.com/issues/27#issuecomment-364514373) on people.canonical.com to be made available through the website.

We should do this by pulling in these files at the point that the docker image is build, probably by making it one of the steps in the Dockerfile, and then make sure it's served up on the website. It doesn't necessarily have to be at https://usn.ubuntu.com/usn-db/database-all.pickle.bz2 etc., but if it's not a redirect should be put in place to redirect that URL to the URL where it is served.

**Comment by WillMoggridge** [comment]
Merge proposal:
https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/337727

**Comment by nottrobin** [comment]
Approved and merged

**Comment by tyhicks** [comment]
@WillMoggridge @nottrobin the deployment fails after this change went in due to a 403 HTTP error code. I'm not sure what is causing it.

**Comment by nottrobin** [comment]
@tyhicks ah yes, IS will need to update the proxy rules to allow those downloads from people.canonical.com through. Apologies, I should have thought of that before merging.

**Comment by nottrobin** [comment]
I've submitted [a request](https://portal.admin.canonical.com/109175) to get this sorted out.

**Comment by nottrobin** [comment]
On the plus side, we got a real-world test of @WillMoggridge's work to retry building the image 3 times on failures :smile:

**Comment by nottrobin** [comment]
Fixed: https://jenkins.canonical.com/webteam/job/deploy-to-usn.ubuntu.com/73/console

**Comment by nottrobin** [comment]
And if you add `162.213.33.20 usn.ubuntu.com` to your hosts file, you can see the database is live at https://usn.ubuntu.com/database/database-all.pickle.bz2, and https://usn.ubuntu.com/usn-db/database-all.pickle.bz2 redirects there.
