### ISSUE TITLE
New usn.ubuntu.com breaks landscape security databse updates.

### ISSUE THREAD

**Issue by simpoir** [canonical/usn.ubuntu.com#32]
In the process of verifying landscape deployments works with the new deployment, I used the following host entry:

162.213.33.205 usn.ubuntu.com

I noticed that some of the landscape scripts for fetching the USN database don't handle redirections and this effectively breaks landscape. Previously the url "https://usn.ubuntu.com/usn-db/database.pickle.bz2" would be served directly. Now it redirects a few times, as such

>  curl -L -I https://usn.ubuntu.com/usn-db/database.pickle.bz2
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.13.7
> Date: Mon, 26 Feb 2018 19:12:22 GMT
> Content-Type: text/html
> Content-Length: 194
> Connection: keep-alive
> Location: http://usn.ubuntu.com/database/database.pickle.bz2
> X-Commit-ID: 90b04e2b83e7715cc960f3910f635471e55d715a
> X-Hostname: usn-ubuntu-com-56874ff86-5wlkd
> Strict-Transport-Security: max-age=15724800; includeSubDomains;
> 
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.13.7
> Date: Mon, 26 Feb 2018 19:12:22 GMT
> Content-Type: text/html
> Content-Length: 185
> Connection: keep-alive
> Location: https://usn.ubuntu.com/database/database.pickle.bz2
> Strict-Transport-Security: max-age=15724800; includeSubDomains;
> 
> HTTP/1.1 200 OK
> Server: nginx/1.13.7
> Date: Mon, 26 Feb 2018 19:12:23 GMT
> Content-Type: application/octet-stream
> Content-Length: 15511897
> Connection: keep-alive
> Last-Modified: Mon, 26 Feb 2018 16:11:04 GMT
> ETag: "5a943198-ecb159"
> X-Commit-ID: 90b04e2b83e7715cc960f3910f635471e55d715a
> X-Hostname: usn-ubuntu-com-56874ff86-qhbd9
> Accept-Ranges: bytes
> Strict-Transport-Security: max-age=15724800; includeSubDomains;
>

**Comment by WillMoggridge** [comment]
Thanks, I have prepared a change to make sure the files are accessible at that URL and also does not redirect back to http from https.

https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/340041

**Comment by simpoir** [comment]
I re-ran checks and it looks good from our side (landscape). Thanks!
