### ISSUE TITLE
database copies via curl feel brittle

### ISSUE THREAD

**Issue by setharnold** [canonical/usn.ubuntu.com#33]
Hello, I noticed in https://code.launchpad.net/%7Eusn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/337727 that there's roughly sixteen `curl` commands run one after the other as part of deploying the new site.

If any one of these fails for any reason, the rest will all fail. The `curl` default is to perform no retries.

If these transfers 'succeed' but only by virtue of copying garbage (say, an HTML page with 404, 403, or 302 text) then this will distribute incorrect contents to clients.

Since many of the copied files are checks on the other copied files, it would be possible to verify the files are correct before serving them to clients.

Thanks

**Comment by tyhicks** [comment]
The `--check` option of the `sha256sum` command can be used, along with the *.sha256 files, to verify the contents. You can see an example of that in this [`fetch-db`](https://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/view/head:/scripts/fetch-db) script.

**Comment by WillMoggridge** [comment]
We have added some retries and verifying the checksum. More can be done so I will leave this open.

We want to look at options for a better solution to hosting these files, this work may move towards that.
