### ISSUE TITLE
The bottom of the release pages scroll horizontally

### ISSUE THREAD

**Issue by tyhicks** [canonical/usn.ubuntu.com#34]
In firefox and chromium-browser, I see this odd thing where the bottom portions of the release-specific pages have horizontally scrolling text. To reproduce what I'm seeing, go to the [16.04 LTS](https://usn.ubuntu.com/releases/ubuntu-16.04-lts/) page and hit the `end` key to go to the bottom of the page.

**Comment by WillMoggridge** [comment]
I didn't expect that it to scroll like that at all.

There is a `<marquee>` element in the body of [3165-1](https://usn.ubuntu.com/3165-1) and it isn't being escaped properly.

**Comment by tyhicks** [comment]
I didn't realize that embedded HTML was valid in markdown. So the Genshi template from the usn-tool project should be escaping all HTML in the USN description?

**Comment by tyhicks** [comment]
[USN-1600-1](https://usn.ubuntu.com/1600-1/) is another example. It includes a `<select>` in the USN description. 

Another is [USN-1364-1](https://usn.ubuntu.com/1364-1/). Its page in contains the following sentence:

`Jüri Aedla discovered that the kernel incorrectly handled /proc//mem permissions.`

However, it should be this (note the `<pid>`):

`Jüri Aedla discovered that the kernel incorrectly handled /proc/<pid>/mem permissions.`

@WillMoggridge is it possible to have hugo not honor HTML in the markdown files? We'd never have a reason to include HTML in the USN descriptions that we'd want rendered in the USN website.

**Comment by WillMoggridge** [comment]
I have been looking at different options but I am not sure Hugo can do much about this. Need to try and escape it before the Markdown is converted and that seems to happen before it is available to the template. I think it may need to be solved in the usn tool.

There is an issue that seems related to this: https://github.com/gohugoio/hugo/issues/1457

I will keep investigating these options right now, though.

**Comment by tyhicks** [comment]
> Need to try and escape it before the Markdown is converted and that seems to happen before it is available to the template. I think it may need to be solved in the usn tool.

Keep in mind that we use usn.py to generate the USN emails, as well, which are created as `Content-Type: text/plain; charset=utf-8` so escaping HTML in those plaintext emails would make them look funny.

**Comment by WillMoggridge** [comment]
Ah yes, I would imagine it would have to be only escaped in the markdown file template and nothing else. Otherwise it risks causing problems.

**Comment by WillMoggridge** [comment]
Here is a proposal to the usn-tool
https://code.launchpad.net/~willmoggridge/usn-tool/sanitizehtml/+merge/340743

And a proposal to this site to update the current content
https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/340744

**Comment by tbille** [comment]
This appears to be fixed
