### ISSUE TITLE
Sort order for releases list

### ISSUE THREAD

**Issue by ejratl** [canonical/usn.ubuntu.com#35]
On the releases page ( https://usn.ubuntu.com/releases/ ) and on the sidebar, it would be nice to have the releases listed in reverse order by date (newest releases at the top of the list).

**Comment by WillMoggridge** [comment]
Thanks, this has been deployed to live

**Comment by matthewpaulthomas** [comment]
This issue has regressed. Perhaps it’s trivial to re-fix in usn.ubuntu.com (and #55 too). If not, I’ll include it as a requirement when speccing the ubuntu.com replacement.
