### ISSUE TITLE
Issue with Advisory URL Redirects

### ISSUE THREAD

**Issue by luckyariane** [canonical/usn.ubuntu.com#37]
It appears the URLs for Ubuntu advisories has recently been updated and while the old links attempt to redirect to the new links a change in the format of the advisory id as it's used in the url makes it fail.

Ex.
Old: http://www.ubuntu.com/usn/USN-3593-1
Redirect: https://usn.ubuntu.com/USN-3593-1 > This leads to a 404 Page
New: https://usn.ubuntu.com/3593-1/

It appears that due to dropping the 'USN-' prefix from the new urls that the redirect fails.

**Comment by tyhicks** [comment]
Thanks for reporting this issue! Can you share where you see the http://www.ubuntu.com/usn/USN-3593-1 link published? I want to make sure that it isn't a URL format that we're publishing to the USN website or to the `ubuntu-security-announce` mailing list.

**Comment by luckyariane** [comment]
I'm not sure if they're still published anywhere, I had existing links to old advisories that are now broken and don't redirect properly which is why I noticed the issue.

**Comment by tyhicks** [comment]
@WillMoggridge I suspect that the rewrite directive below is case-sensitive:

```
    # Redirect old USN paths to new format
    # /usn/usn-0123-1 -> /0123-1
    if ($request_uri ~* ^/usn/usn-([a-zA-Z0-9\-]+)/?$) {
        rewrite ^/usn/usn-([a-zA-Z0-9\-]+)/?$ $redirect_domain/$1 permanent;
    }
```

You know how to configure nginx better than I do so I'll leave it up to you.
