### ISSUE TITLE
RSS feed returns 404

### ISSUE THREAD

**Issue by r-daneel** [canonical/usn.ubuntu.com#44]
The [rss feed](https://usn.ubuntu.com/usn/rss.xml) url on the [usn main page](https://usn.ubuntu.com/) returns 404.
The [atom feed](https://usn.ubuntu.com/usn/atom.xml) seems to be ok.

**Comment by tbille** [comment]
It seems to be fine, reopen if you encounter it again. Thanks

**Comment by r-daneel** [comment]
indeed, seems to be ok now. thanks.
