### ISSUE TITLE
Fonts loaded over http, which means Chrome/Firefox won't actually load them

### ISSUE THREAD

**Issue by BryanQuigley** [canonical/usn.ubuntu.com#48]
## Summary
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,700,300italic,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>

change them to https should fix it IIUC.  Alternatively hosting those fonts locally would work too.

error log:
Mixed Content: The page at 'https://usn.ubuntu.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Ubuntu:300,400,700,300italic,400italic,700italic'. This request has been blocked; the content must be served over HTTPS.
(index):19 Mixed Content: The page at 'https://usn.ubuntu.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Ubuntu+Mono'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://usn.ubuntu.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Ubuntu:300,400,700,300italic,400italic,700italic'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://usn.ubuntu.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Ubuntu+Mono'. This request has been blocked; the content must be served over HTTPS.

## Process
Load usn homepage,
Open browser console to see errors

## Current and expected result
Current: page has blocked elements in both Chrome and Firefox.
Expected: Shows as secure

Thanks!
Bryan

**Comment by stevebeattie** [comment]
Proposed fix at https://git.launchpad.net/~sbeattie/usn.ubuntu.com/log/?h=fix-http-google-fonts

**Comment by setharnold** [comment]
Steve's patch looks good to me, thanks.

**Comment by stevebeattie** [comment]
This was fixed in https://git.launchpad.net/usn.ubuntu.com/commit/?id=b9949e93dc299b9c28245012030a80dcb872b5b7 . Thanks!
