### ISSUE TITLE
Releases ordered correctly on front page, incorrectly on other pages

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/usn.ubuntu.com#49]
1\. Go to [usn.ubuntu.com](https://usn.ubuntu.com/).
2\. Look at the list of releases on the right.
3\. Follow [any of the release links](https://usn.ubuntu.com/releases/ubuntu-18.04-lts/).
4\. Look at the list of releases on the right.

What you see:

2\. The releases are listed most recent first.|4\. The releases are listed reverse-alphabetically.
-|-
![usn ubuntu com-releases-front](https://user-images.githubusercontent.com/19801137/45154115-59a27b00-b1ce-11e8-85a7-89b775af9f78.png)|![usn ubuntu com-releases-release](https://user-images.githubusercontent.com/19801137/45154114-59a27b00-b1ce-11e8-900a-81c290ba1cbe.png)

What you should see:
4\. The releases are listed most recent first.

**Comment by nottrobin** [comment]
Fix proposed in https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/356504 - @tbille could you review that for me?
