### ISSUE TITLE
tzdata missing for Ubuntu 18.04

### ISSUE THREAD

**Issue by erinus** [canonical/usn.ubuntu.com#53]
## Summary
For Ubuntu 18.04, tzdata in apt repository is tzdata_2018f-0ubuntu0.18.04_all.deb, but apt source list is still tzdata_2018e-0ubuntu0.18.04_all.deb.

## Process
On Ubuntu 18.04
>sudo apt-get update
>sudo apt-get install php7.2 php7.2-dev php7.2-fpm php7.2-cli php7.2-common

## Current and expected result
Current: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_2018e-0ubuntu0.18.04_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Expected: tzdata package is installed successfully.

## Screenshot
![error1](https://user-images.githubusercontent.com/4888506/47612606-33f06e80-dab9-11e8-8a6b-c0d75647562a.png)

**Comment by setharnold** [comment]
I believe you have a local misconfiguration.

You can see that the 2018f version is available on the security.ubuntu.com server:

http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/

And if you download and decompress this Packages.gz file you'll see that the tzdata package is properly described:

http://security.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-amd64/Packages.gz


```
Package: tzdata
Architecture: all
Version: 2018f-0ubuntu0.18.04
Multi-Arch: foreign
Priority: important
Section: libs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3020
Provides: tzdata-buster
Depends: debconf (>= 0.5) | debconf-2.0
Replaces: libc0.1, libc0.3, libc6, libc6.1
Filename: pool/main/t/tzdata/tzdata_2018f-0ubuntu0.18.04_all.deb
Size: 188344
MD5sum: e21a1c2a93b72eb896d47c05701737ac
SHA1: d3991f53af7eb9499393cfcd04a63333c170bf28
SHA256: 3567e2f46a9354c5ace80c83544d3d1eb407b00594a465e5af74fa857a110a09
Homepage: https://www.iana.org/time-zones
Description: time zone and daylight-saving time data
Task: minimal
Description-md5: a77a3cc9a67658dd7cfdc6547391b8f8
Supported: 5y
```

I'm surprised your apt is contacting this server for this file anyway -- all the security updates are mirrored into `updates` every few hours, to place them on the wider mirror network, and reduce the load on the security.ubuntu.com servers. (My local archive mirror received this file from the main archives before `Wed Oct 24 15:07 2018`. Probably that time is in -0700. Either way it's from a few days ago...)

Please double-check your `/etc/apt/sources.list` file, any apt pinning that might be place, dpkg holds, etc. If you can't spot it, please reply with the output from `apt-get update` and `apt-cache policy tzdata`.

Thanks

**Comment by erinus** [comment]
Thanks. My Dockerfile content is:

```
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y dist-upgrade

RUN apt-get install -y ca-certificates vim git curl wget cron nginx
RUN apt-get install -y nginx
RUN apt-get install -y php7.2 php7.2-dev php7.2-fpm php7.2-cli php7.2-common
```

I will try to add
```
RUN apt-cache policy tzdata
```
before I install PHP.

Thanks for your help.

**Comment by erinus** [comment]
My Dockerfile
```
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y dist-upgrade

RUN apt-cache policy tzdata

RUN apt-get install -y ca-certificates vim git curl wget cron nginx
RUN apt-get install -y nginx
RUN apt-get install -y php7.2 php7.2-dev php7.2-fpm php7.2-cli php7.2-common
```

Still failed with same reason
```
Get:110 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 php7.2 all 7.2.10-0ubuntu0.18.04.1 [9248 B]
Get:111 http://archive.ubuntu.com/ubuntu bionic/main amd64 shtool all 2.0.8-9 [121 kB]
Get:112 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 php7.2-dev amd64 7.2.10-0ubuntu0.18.04.1 [555 kB]
Get:113 http://archive.ubuntu.com/ubuntu bionic/main amd64 pkg-php-tools all 1.35ubuntu1 [27.8 kB]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_2018e-0ubuntu0.18.04_all.deb  404  Not Found [IP: 91.189.88.149 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 57.7 MB in 3min 59s (241 kB/s)
The command '/bin/sh -c apt-get install -y php7.2 php7.2-dev php7.2-fpm php7.2-cli php7.2-common' returned a non-zero code: 100
```

**Comment by anthonydillon** [comment]
@erinus sorry to hear you are having a issue with Ubuntu. Please, raise this issue on askubuntu.com or on [our community discourse](https://community.ubuntu.com/). This repo is for the website and issues relating to it.
