### ISSUE TITLE
Not a bug, but a typo

### ISSUE THREAD

**Issue by wkoenig365** [canonical/usn.ubuntu.com#54]
## Summary

The copyright notice in the footer still states 2017, not 2019.

## Process

Visit usn.ubuntu.com and scroll to the bottom of the page.

## Current and expected result

Currently states a copyright of 2017, expected 2019.

**Comment by stevebeattie** [comment]
Thanks for the report.

I've created a branch https://git.launchpad.net/~sbeattie/usn.ubuntu.com/log/?h=fixup-copyright to address this in a way such that we don't need to update it each year (also, an update to the README.md slipped in). It worked with local testing with hugo, but would like review. Thanks!

**Comment by stevebeattie** [comment]
I've now pushed the branch above to master, along with a follow up commit to correct the copyright statement in the generated rss.xml file as well. Thanks again for the report!

**Comment by wkoenig365** [comment]
Not a problem! I just got around to checking out your branch (busy day at work). All looked well to me especially given the small amount of diffs with the master branch. I don't see any issue with using the `now.Format` function either. Local testing checked out on my box as well. Keep up the good work Steve!
