### ISSUE TITLE
Manage page cache expirations

### ISSUE THREAD

**Issue by ghost** [canonical/usn.ubuntu.com#56]
Now that the site is fronted by the website-content-cache project, its default (1d) was found to be insufficient for usn.ubuntu.com, for the home page and rss.xml.  For the moment, we've reduced it down to 1h for usn.ubuntu.com, but we'd like it if the Cache-Control were set on the origin side.  I'm thinking:

* / and /rss.xml at 1h.
* Default without explicit expiration (at which point we can set it back to the content-cache default of 1d), as the individual USN pages are more or less invariant.

FWIW, here's the docs on how nginx determines to revalidate a page:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_valid

**Comment by nottrobin** [comment]
I guess for this we'll have to coybow some `cache-control` headers into [nginx.conf](https://git.launchpad.net/usn.ubuntu.com/tree/nginx.conf) while we wait to move it over to ubuntu.com. When it's there we can do something more dynamic.

**Comment by nottrobin** [comment]
MP filed: https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/378385

**Comment by nottrobin** [comment]
We agreed that our default cache time for most pages on most of our sites should be 5 minutes, unless there's a reason for it to be different. We are tracking the work to roll that out everywhere in this issue:
https://github.com/canonical-web-and-design/web-squad/issues/2312

So I've  updated my MP to send `cache-control: public; max-age=300` for all endpoints.

**Comment by nottrobin** [comment]
This is now live:

``` bash
$ curl -I https://usn.ubuntu.com/445-1/
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Mon, 10 Feb 2020 12:16:58 GMT
Content-Type: text/html
Strict-Transport-Security: max-age=15724800
Last-Modified: Mon, 10 Feb 2020 12:14:04 GMT
ETag: W/"5e41490c-1453"
x-vcs-revision: always
x-hostname: usn-ubuntu-com-5dd6545d89-fksgv
Cache-Control: public; max-age=300
Content-Encoding: gzip
Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect
X-Cache-Status: HIT from content-cache/1
```
